# Python: "3.8", "3.9", "3.10"
# OS: ubuntu-20.04, ubuntu-latest
# OS: macOS-10.15


name: Python package

on:
  push:
    branches: [ deploy ]
  pull_request:
    banches: [ deploy ]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build_unix:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-benchmark build
        python -m pip install numpy scipy matplotlib>=3.0.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Compile and install
      run: |
        python -m pip install . -v
    - name: Test installation
      run : |
        python ./util/check_installation.py
    - name: Test with pytest
      run: |
        pytest --ignore=venv --benchmark-skip
    - name: Build
      run: |
        python -m build

